version: '3.4'

services:
  server:
    image: wirvonhier/server:test-1596983928
    networks:
      - servernet
    # logging: # TODO
    secrets:
      - test_mongo_user
      - test_mongo_password
      - test_sendgrid_api_key
      - test_cloudinary_api_key
      - test_cloudinary_api_secret
      - test_vimeo_access_token
    environment:
        CLIENT_BASE_URL: https://test.wirvonhier.net
        APP_DOMAIN: wirvonhier.net
        NODE_ENV: production
        PORT: 3000
        MONGO_USER_FILE: /run/secrets/test_mongo_user
        MONGO_PASSWORD_FILE: /run/secrets/test_mongo_password
        MONGO_PATH: mongo:27017/wirvonhier
        MONGO_AUTH_SOURCE: wirvonhier
        SENDGRID_API_KEY_FILE: /run/secrets/test_sendgrid_api_key
        CLOUDINARY_CLOUD_NAME: wirvonhier
        CLOUDINARY_API_KEY_FILE: /run/secrets/test_cloudinary_api_key
        CLOUDINARY_API_SECRET_FILE: /run/secrets/test_cloudinary_api_secret
        VIMEO_ACCESS_TOKEN_FILE: /run/secrets/test_vimeo_access_token
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      resources:
        limits:
          memory: 4G

  client:
    image: wirvonhier/client:test-1596937176
    networks:
      - clientnet
    # logging: # TODO      
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      resources:
        limits:
          memory: 4G

  proxy:
    image: wirvonhier/proxy:test-1596975164
    restart: always
    networks:
      - clientnet
      - servernet
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    # logging: # TODO
    secrets:
      - test_client_ssl_pub_key
      - test_client_ssl_priv_key
      - test_server_ssl_pub_key
      - test_server_ssl_priv_key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    deploy:
      mode: "replicated"
      resources:
        limits:
          memory: 4G

  mongo:
    image: wirvonhier/mongo:test-1596983790
    networks:
      - servernet
    # ports:
    #   - 27018:27017
    # logging: # TODO
    secrets:
      - test_mongo_initdb_root_password
      - test_mongo_initdb_root_username
      - test_mongo_password
      - test_mongo_user
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/test_mongo_initdb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/test_mongo_initdb_root_password
      MONGO_USER_FILE: /run/secrets/test_mongo_user
      MONGO_PASSWORD_FILE: /run/secrets/test_mongo_password
      MONGO_INITDB_DATABASE: wirvonhier
    volumes:
      - mongodbdata:/data/db
    deploy:
      mode: "replicated"
      resources:
        limits:
          memory: 4G

volumes:
  mongodbdata:

networks:
  clientnet:
  servernet:

secrets:
  test_mongo_initdb_root_username:
    external: true
  test_mongo_initdb_root_password:
    external: true
  test_mongo_user:
    external: true
  test_mongo_password:
    external: true
  test_sendgrid_api_key:
    external: true
  test_cloudinary_api_key:
    external: true
  test_cloudinary_api_secret:
    external: true
  test_vimeo_access_token:
    external: true
  test_google_maps_api_key:
    external: true
  test_client_ssl_pub_key:
    external: true
  test_client_ssl_priv_key:
    external: true
  test_server_ssl_pub_key:
    external: true
  test_server_ssl_priv_key:
    external: true
    